global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.


remote_write:
  - url: 
    basic_auth:
      username: 
      password: 
scrape_configs:
  # Job for scraping prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: snmp_exporter
    static_configs:
      - targets: ['10.4.20.42']  # NAS IP
    metrics_path: /snmp
    params:
      auth: [public_v3]
      module: [synology]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__param_target]
        regex: (.*)
        replacement: snmp_exporter:9116
        target_label: __address__
